Repository jenkinsci/plugin-pom, pull requests merged in 2019-06, with the labels that each got.

#207 [JENKINS-57852] - Deprecate Java 7 targets support in Plugin POM
  README.md
  pom.xml
  src/it/not-newest-java-level/invoker.properties
  src/it/not-newest-java-level/pom.xml
  src/it/not-newest-java-level/src/main/java/test/X.java
  src/it/not-newest-java-level/src/main/resources/index.jelly
  src/it/sample-plugin/pom.xml
Labels: deprecated

#206 [JENKINS-57425] Add profile to run benchmarks only when the `benchmark` property is set
  README.md
  pom.xml
  src/it/benchmark/invoker.properties
  src/it/benchmark/pom.xml
  src/it/benchmark/postbuild.groovy
  src/it/benchmark/src/test/java/benchmark/BenchmarkRunner.java
  src/it/benchmark/src/test/java/benchmark/DontRunMeTest.java
  src/it/benchmark/src/test/java/benchmark/SampleBenchmark.java
Labels: enhancement

#213 Update Jenkins Test Harness from 2.50 to 2.51
  pom.xml
  src/it/benchmark/src/test/java/benchmark/BenchmarkRunner.java
Labels: dependencies
