Repository jenkinsci/plugin-pom, pull requests merged in 2019-12, with the labels that each got.

#267 make dependabot ignore jenkins bom/war updates
  .dependabot/config.yml
Labels: internal

#269 [JENKINS-60474] streamline the pom and support the jenkins-bom
  CONTRIBUTING.adoc
  Jenkinsfile
  README.md
  pom.xml
  src/it/benchmark/invoker.properties
  src/it/benchmark/pom.xml
  src/it/beta-fail/pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/beta-pass/pom.xml
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/sample-plugin/pom.xml
  src/it/undefined-java-level/pom.xml
Labels: breaking, enhancement, internal, removed

#274 Remove the obsolete baselines section from README
  README.md
Labels: documentation

#209 [JENKINS-58028] - Switch from gmaven to gmavenplus + Remove gmaven from `dependencyManagement`, gmavenplus should be used instead
  pom.xml
Labels: enhancement, removed

#277 Remove another incarnation of the gmaven plugin reference
  pom.xml
Labels: removed
