Repository jenkinsci/plugin-pom, pull requests merged in 2019-11, with the labels that each got.

#247 Add a license badge to README
  README.md
Labels: documentation, hacktoberfest

#252 Revert the BOM support from 3.52 to fix incremental plugin builds + Add integration tests for Incrementals
  README.md
  pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/incrementals-and-plugin-bom/.mvn/extensions.xml
  src/it/incrementals-and-plugin-bom/.mvn/maven.config
  src/it/incrementals-and-plugin-bom/invoker.properties
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/incrementals-and-plugin-bom/postbuild.groovy
  src/it/incrementals-and-plugin-bom/src/main/java/io/jenkins/plugins/RandomClass.java
  src/it/incrementals-and-plugin-bom/src/main/resources/index.jelly
  src/it/incrementals-and-plugin-bom/src/test/java/io/jenkins/plugins/RandomClassTest.java
Labels: bug, internal

#253 CI improvements
  Jenkinsfile
  pom.xml
  src/it/benchmark/invoker.properties
  src/it/beta-fail/invoker.properties
  src/it/beta-fail/postbuild.groovy
  src/it/beta-just-testing/invoker.properties
  src/it/beta-pass/invoker.properties
  src/it/incrementals-and-plugin-bom/invoker.properties
  src/it/sample-plugin/invoker.properties
  src/it/undefined-java-level/invoker.properties
  src/it/undefined-java-level/postbuild.groovy
Labels: internal

#257 Re-introduce the Jenkins Core BOM support + Update Animal Sniffer from 1.17 to 1.18
  README.md
  pom.xml
  src/it/beta-just-testing/pom.xml
Labels: dependencies, enhancement

#261 README: update the changelog badge text to make it more explicit
  README.md
Labels: documentation

#258 Add phase to animal-sniffer to fix mvn test
  pom.xml
Labels: bug
