Repository jenkinsci/plugin-pom, pull requests merged in 2020-01, with the labels that each got.

#282 Add link to show all BOM versions
  README.md
Labels: documentation

#283 jenkins-test-harness.version=2.60
  pom.xml
Labels: dependencies

#284 [JENKINS-60694] - Update Jenkins Test Harness to 2.60 with the hanging injected test fix
  pom.xml
Labels: bug
