Repository jenkinsci/plugin-pom, pull requests merged in 2021-07, with the labels that each got.

#419 Require Maven 3.8.1
  pom.xml
Labels: breaking

#425 Revert Spotbugs upgrade to 4.3.0
  .github/dependabot.yml
  pom.xml
Labels: dependencies

#426 [JENKINS-66247] Do not override the version of `annotation-indexer` from core
  pom.xml
  src/it/beta-fail/pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/beta-pass/pom.xml
Labels: bug

#427 [JENKINS-66247] Pick up more compatible `access-modifier-checker`
  pom.xml
  src/it/beta-fail/pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/beta-pass/pom.xml
Labels: bug

#428 Bogus errors about `@Restricted(NoExternalUse.class)` as in `localizer-maven-plugin`
  pom.xml
  src/it/localizer/invoker.properties
  src/it/localizer/pom.xml
  src/it/localizer/src/main/java/test/X.java
  src/it/localizer/src/main/resources/index.jelly
  src/it/localizer/src/main/resources/test/Messages.properties
  src/it/localizer/src/test/java/test/XTest.java
Labels: bug
