Repository jenkinsci/plugin-pom, pull requests merged in 2021-12, with the labels that each got.

#465 Ban vulnerable versions of Apache Log4j 2
  pom.xml
Labels: enhancement

#467 Exclude JSR 305
  pom.xml
Labels: removed

#469 Exclude `javax.servlet:servlet-api`
  pom.xml
Labels: dependencies

#470 Get annotation versions from core BOM
  pom.xml
Labels: enhancement

#471 Update extra-enforcer-rules to 1.5.1
  pom.xml
Labels: bug

#472 Update versions in README
  README.md
Labels: documentation

#473 Bump `access-modifier` from 1.25 to 1.27
  pom.xml
Labels: dependencies

#476 Bump `jenkins-test-harness` from 1666.vd1360abbfe9e to 1674.v3b8b1441e939
  pom.xml
Labels: dependencies

#477 Work around issues on 2.222.x, 2.235.x, and 2.289.x
  pom.xml
Labels: bug

#479 Adopt POM Code Convention
  pom.xml
Labels: internal

#480 Bump Jenkins version to 2.249; clean up plugin parent POM
  README.md
  pom.xml
  src/it/benchmark/pom.xml
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/sample-plugin/pom.xml
  src/it/undefined-java-level/pom.xml
Labels: enhancement

#482 Sort a few dependencies in the `dependencyManagement` section
  pom.xml
Labels: internal
