Repository jenkinsci/plugin-pom, pull requests merged in 2022-03, with the labels that each got.

#511 [JENKINS-67960] Work around MCOMPILER-346
  pom.xml
Labels: bug

#512 Move away from deprecated Release Drafter App
  .github/workflows/release-drafter.yml
Labels: chore

#522 Deprecate `java.level`
  README.md
  pom.xml
  src/it/benchmark/pom.xml
  src/it/beta-fail/pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/beta-pass/pom.xml
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/localizer/pom.xml
  src/it/sample-plugin/pom.xml
  src/it/undefined-java-level/invoker.properties
  src/it/undefined-java-level/pom.xml
  src/it/undefined-java-level/postbuild.groovy
  src/it/undefined-java-level/src/main/java/test/X.java
  src/it/undefined-java-level/src/main/resources/index.jelly
Labels: deprecated

#524 Introduce `jenkins.addOpens`
  pom.xml
Labels: enhancement

#523 [JENKINS-54842] Define compiler configuration with Maven properties where possible and use Java 11 built-in functionality instead of Animal Sniffer
  pom.xml
Labels: internal

#525 Introduce `jenkins.insaneHook`
  pom.xml
Labels: enhancement
