Repository jenkinsci/plugin-pom, pull requests merged in 2022-11, with the labels that each got.

#629 Upgrade SpotBugs from 4.2.3 to 4.7.2.1
  .github/dependabot.yml
  pom.xml
Labels: dependencies

#628 Remove duplicate SpotBugs defaults
  pom.xml
Labels: internal

#631 Support a SpotBugs exclude filter file for Maven multi-module projects
  pom.xml
Labels: bug

#634 Remove managed dependency on Objenesis
  pom.xml
Labels: removed

#635 Sort `<pluginManagement>` entries by group ID and artifact ID
  pom.xml
Labels: skip-changelog

#636 Sort `<dependencyManagement>` section by scope, group ID, and artifact ID
  pom.xml
Labels: skip-changelog

#625 Remove `--mutex network` argument for Yarn builds
  pom.xml
Labels: breaking

#640 Group version properties together
  pom.xml
Labels: skip-changelog

#643 Document Java 17 support
  README.md
Labels: documentation

#645 Define `surefire.forkNumber` in Surefire JVM
  pom.xml
Labels: enhancement

#648 Use `project.basedir` rather than `maven.multiModuleProjectDirectory`
  pom.xml
Labels: bug

#478 [JENKINS-68568] Require Java 11 or newer
  README.md
  pom.xml
  src/it/benchmark/pom.xml
  src/it/beta-fail/pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/beta-pass/pom.xml
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/localizer/pom.xml
  src/it/sample-plugin/pom.xml
Labels: enhancement, removed, breaking, squash-merge-me
