Repository jenkinsci/plugin-pom, pull requests merged in 2022-04, with the labels that each got.

#529 Provide a default value of `jenkins.addOpens` for the benefit of IDEs
  pom.xml
Labels: bug

#530 Setting `source` and `target` are unnecessary when setting `release`
  pom.xml
Labels: internal

#531 Avoid unnecessary defining and clearing of properties
  pom.xml
Labels: skip-changelog

#534 Remove unneeded SUREFIRE-1226 workaround
  pom.xml
Labels: chore
