Repository jenkinsci/plugin-pom, pull requests merged in 2023-07, with the labels that each got.

#801 Adapt maven-license-plugin changes
  pom.xml
Labels: breaking

#802 Flatten repositories from JEP-229 plugins
  pom.xml
  src/it/cd-plugin/.mvn/extensions.xml
  src/it/cd-plugin/.mvn/maven.config
  src/it/cd-plugin/invoker.properties
  src/it/cd-plugin/pom.xml
  src/it/cd-plugin/postbuild.groovy
  src/it/cd-plugin/src/main/resources/index.jelly
Labels: bug

#810 Test on Java 17 by default
  Jenkinsfile
Labels: test
