Repository jenkinsci/plugin-pom, pull requests merged in 2023-05, with the labels that each got.

#753 dependabot ignore jakarta.servlet:jakarta.servlet-api >= 5.0.0
  .github/dependabot.yml
Labels: dependencies

#752 Remove `spotless.check.skip` from `quick-build` profile
  pom.xml
Labels: breaking

#762 Replace 'hamcrest-core' with 'hamcrest'
  pom.xml
Labels: removed
