Repository jenkinsci/plugin-pom, pull requests merged in 2023-04, with the labels that each got.

#733 Enable Spotless for automatic formatting
  README.md
  pom.xml
Labels: enhancement

#742 Activate Spotless via Maven property rather than file
  README.md
  pom.xml
  src/it/benchmark/pom.xml
  src/it/benchmark/src/test/java/benchmark/BenchmarkRunner.java
  src/it/benchmark/src/test/java/benchmark/SampleBenchmark.java
  src/it/beta-fail/downstream/pom.xml
  src/it/beta-fail/downstream/src/main/java/downstream/Caller.java
  src/it/beta-fail/pom.xml
  src/it/beta-fail/postbuild.groovy
  src/it/beta-fail/upstream/pom.xml
  src/it/beta-fail/upstream/src/main/java/upstream/Api.java
  src/it/beta-just-testing/downstream/pom.xml
  src/it/beta-just-testing/downstream/src/main/java/downstream/NotCaller.java
  src/it/beta-just-testing/downstream/src/test/java/downstream/ApiTest.java
  src/it/beta-just-testing/pom.xml
  src/it/beta-just-testing/upstream/pom.xml
  src/it/beta-just-testing/upstream/src/main/java/upstream/Api.java
  src/it/beta-pass/downstream/pom.xml
  src/it/beta-pass/downstream/src/main/java/downstream/Caller.java
  src/it/beta-pass/pom.xml
  src/it/beta-pass/upstream/pom.xml
  src/it/beta-pass/upstream/src/main/java/upstream/Api.java
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/incrementals-and-plugin-bom/src/main/java/io/jenkins/plugins/RandomClass.java
  src/it/incrementals-and-plugin-bom/src/test/java/io/jenkins/plugins/RandomClassTest.java
  src/it/localizer/pom.xml
  src/it/localizer/src/main/java/test/X.java
  src/it/localizer/src/test/java/test/XTest.java
  src/it/sample-plugin/pom.xml
  src/it/sample-plugin/src/main/java/test/SampleRootAction.java
  src/it/sample-plugin/src/test/java/test/SampleRootActionTest.java
Labels: internal

#747 Remove file-based Spotless activation
  pom.xml
Labels: removed

#693 Upgrade from `javax.servlet-api-3.1` to `jakarta.servlet-api:4.0` and ban javax.servlet:javax.servlet-api
  pom.xml
  src/it/servlet-api/invoker.properties
  src/it/servlet-api/pom.xml
  src/it/servlet-api/src/main/resources/index.jelly
  src/it/servlet-api/src/test/java/test/ServletAPITest.java
Labels: bug, developer
