Repository jenkinsci/plugin-pom, pull requests merged in 2024-10, with the labels that each got.

#1016 Add docs for frontend integration + opt-in for Jenkins integration
  README.md
  pom.xml
Labels: documentation, enhancement

#1030 Update version of parent pom for Java 17 being required
  README.md
Labels: documentation

#1034 Work around jenkinsci/plugin-pom#1032
  pom.xml
Labels: bug

#1042 Fix doc since marker files are dotfiles
  README.md
Labels: documentation
