Repository jenkinsci/plugin-pom, pull requests merged in 2024-04, with the labels that each got.

#914 [JENKINS-72956] Skip Spotless in quick-build profile
  pom.xml
Labels: developer

#916 Work around ASM require upper bound dependencies error
  pom.xml
Labels: bug

#922 Suppress Javadoc timestamp
  pom.xml
Labels: enhancement
