Repository jenkinsci/plugin-pom, pull requests merged in 2024-09, with the labels that each got.

#1002 Revert "Bump org.jenkins-ci.tools:maven-hpi-plugin from 3.57 to 3.58"
  pom.xml
Labels: skip-changelog

#1008 Do not ignore `mvntest` failure
  pom.xml
Labels: bug

#1004 [JENKINS-73339] Require Java 17 and Jetty 12 (EE 9) for plugin development
  .github/dependabot.yml
  README.md
  pom.xml
  src/it/benchmark/pom.xml
  src/it/beta-fail/pom.xml
  src/it/beta-just-testing/pom.xml
  src/it/beta-pass/pom.xml
  src/it/cd-plugin/pom.xml
  src/it/incrementals-and-plugin-bom/pom.xml
  src/it/localizer/pom.xml
  src/it/sample-plugin/pom.xml
  src/it/servlet-api/pom.xml
Labels: enhancement

#1018 Require Maven 3.9.6 or later
  pom.xml
Labels: bug

#1017 Add 'may-spotless-apply' profile
  README.md
  pom.xml
Labels: enhancement
