Repository jenkinsci/plugin-pom, pull requests merged in 2025-05, with the labels that each got.

#1123 Enable `toggleOffOn` feature for spotless
  pom.xml
Labels: enhancement

#1134 Fix duplicate declaration of `maven-antrun-plugin`
  pom.xml
Labels: bug

#1138 Set `jenkins.javaAgent` in `TestRuntimeMojo`
  pom.xml
Labels: bug

#1145 Improve phrasing of benchmark instructions
  README.md
Labels: documentation
